image: "evilbeaver/onescript:latest"

stages:
  - build
  - test
  - deploy
 
build:
  stage: build
  script: 
  - grep '%ver' -P -R -I -l  packagedef | xargs sed -i 's/%ver/$CI_COMMIT_REF_NAME/g' 
  - mkdir ./build
  - opm build . -out ./build
  - opm install ./build/daSklonenie-$CI_COMMIT_REF_NAME.ospx
  artifacts:
    paths:
    - build/

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script: 
  - opm install 1testrunner
  - 1testrunner -runall ./tests

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
  - echo "deploy"
  artifacts:
    name: "daSklonenie-$CI_COMMIT_REF_NAME.ospx"
    paths:
    - build/